### PR TITLE
Rewritten socket code to support Python 3.13...

### PR DESCRIPTION
**Pull request by m-wichmann**
...by replacing telnetlib with raw sockets. Library telnetlib was removed in Python 3.13 so this addon currently does not work on e.g. Fedora 41. The port is pretty straight forward, since the old code already used the raw sockets from the telnet object. Only `socket_read_until_newline()` needed to be rewritten because the socket API does not offer a similar function. The socket library hasn't changed substantially in a while, so this change should also work with older Python versions (not testen yet).

### CODE REVIEW

**Comment by herrnst** [comment]
Thank you very much for taking on that telnetlib matter! While this is basically looking very good, maybe there's something to improve on the read-until function (at some time I started playing around with the raw sockets but never got to actually implement this in script.xbmc.lcdproc...) - please see my inline comments.

**Comment by m-wichmann** [comment]
Sorry, but I can't see any inline comments (maybe forget sending them). But I'm also not really happy with the read function either. I'm going to see if I can rewrite it somehow.

Anyway, I did mess up the timeout calculation (ms vs s) in the first version. It's fixed in the one I just pushed. I also added a call to `socket.settimeout`, so the `recv()` call can't block indefinitely anymore.

**Comment by herrnst** [comment]
Strange re the inline comments.

So I just picked your last version ontop of HEAD and applied the changes I had in mind, all into the [rawsocket](https://github.com/herrnst/script.xbmc.lcdproc/commits/rawsocket/) branch:

Your (last) commit: https://github.com/herrnst/script.xbmc.lcdproc/commit/f501c6c6dbc0729c93e7cd82e9879f7a7f60321f
Changes I had in mind: https://github.com/herrnst/script.xbmc.lcdproc/commit/f9007a267d6e0f9d754248a4ba096b73a2c0093b

This is completely untested and wasn't run from inside Kodi (maybe I'll find some time later today), but you should get the idea.

**Comment by m-wichmann** [comment]
I just tested your latest changes and it works great. Code looks good to me as well. I wouldn't mind if you'd just merged your branch and I'd close this PR.

**Comment by herrnst** [comment]
Thanks for taking a look and testing! Well, if this would be okay for you, I'd put something more meaningful than "fixup" into the commit message, then apply two or three additional changes ontop (ie. cleanup the CR and decode mess when returning values from ReadUntil()), and maybe you can give the result an additional test.

If everything is okay, I would merge this PR so you're properly credited (you initiated these overdue changes, so THANKS ALOT FOR THIS) and then merge the remainings right away into master. I think this qualifies for a new release then, which will go to the official repo-scripts as an update for everyone then.

**Comment by herrnst** [comment]
So, added the mentioned changes to the rawsocket branch, installed onto the HTPC and testing right now. Please test aswell, and if things still work for you (in comparison to the old telnetlib implementation) please let me know - I'll do the "merge this PR, stuff the other changes on top and draft a release" dance afterwards.

**Comment by m-wichmann** [comment]
Your newest changes work great. I also did a quick code review and spotted two small things:
1. In line 324 there is a `%s` format modifier, but the data is missing (`log(LOGERROR,"Connect(): Caught %s during hello/info phase, aborting.")`)
2. There are still some mentions of telnet in a couple of comments and log messages that could be removed

But other than that it looks good to me.

**Comment by herrnst** [comment]
> Your newest changes work great. I also did a quick code review and spotted two small things:
> 
> 1. In line 324 there is a `%s` format modifier, but the data is missing (`log(LOGERROR,"Connect(): Caught %s during hello/info phase, aborting.")`)

Oh, good catch, thanks! Fixed that up in the corresponding commit.

> 2. There are still some mentions of telnet in a couple of comments and log messages that could be removed

Yeah, removed the few mentions of telnet with the "be verbose" commit aswell and made the calls to log() in SendCommand() more meaningful like in Connect().

> But other than that it looks good to me.

Thanks! And again thanks for getting this going in the first run! :) Will merge now and push everything to master, and if things won't show signs of breakage the next days, I'll draft 4.1.0.

**Pull request merged**
