### PR TITLE
Add options to enable time on progressbar

### PR DESCRIPTION
**Pull request by truongtx8**
This code will create time elapsed/totat at begin/end of progressbar like this:
00:12:34 |||||||||||||-------- 01:23:45
Useful for who has glcd or char with 16+ columns.

### CODE REVIEW

**Comment by herrnst** [comment]
I like the idea of displaying progressbars in this way, however, I'd rather see something like this be implemented as a line type instead of a switch which changes the complete progress bar display (so it gets handles as something like LCD_LINETYPE_PROGRESSTIME or so).

Also, you should squash the two commits into one, and while at it, please also fix the authors.

**Comment by truongtx8** [comment]
Squashed commits and added author infor.
Implement new line type may take sometime since I'm new in Python but I will try.

For now, each modificaion in code, I need to restart Kodi to check the effect. Is there a faster way to update/restart add-on for faster coding?

Thanks so much.

**Comment by herrnst** [comment]
Oh, with authors I meant the GIT commit author, not the actual file headers.

You don't need to restart Kodi everytime you change the python code, just go to the addon manager and deactivate/activate the addon. Note that especially the LCDproc server can get messed up due to unclean disconnects if the script is stopped because of syntax errors.

**Comment by truongtx8** [comment]
Updated.
I tried your method before but my Kodi 15.1 often freeze few seconds to minute when I enable/disable add-on. Restart Kodi seems faster.

**Pull request closed without merging**
