### PR TITLE
Add forced 4-digit big clock mode in LCD.xml

### PR DESCRIPTION
**Pull request by mskalski**
Add possibility to force 4-digit `TimeWide` InfoLabel for clock with current time
(with format `mm:ss`) on displays with 20 and more columns.

By default format `hh:mm:ss` is used, which usually doesn't look good on LCD.

### CODE REVIEW

**Comment by herrnst** [comment]
The configuration related changes look ok, though the changes that update the behaviour look a bit strange atm. I need to take a more thorough look on that and do some tests.

**Comment by mskalski** [comment]
Well change is simple: Number of possible to display big digits is decided after connecting do LCDd and reading display size. but at this stage settings from LCD.xml are not read yet.

So I decided just to modify `GetBigDigitTime()` function to return time in format `hh:mm` if configured so (`self.m_bFourDigitBigClock` is `True`) or if display is not enough large (if has space for less than 8 big digits). Otherwise (if not configured or if has 8 big digits) `hh:mm:ss` is returned.

In fact these conditions are reversed.

**Comment by herrnst** [comment]
I'll take a closer look at this in the next days.

**Comment by mskalski** [comment]
@herrnst, what do you think about adding this setting `fourdigitbigclock` to GUI settings?

**Comment by herrnst** [comment]
I think I'll implement this a bit different, namely have a setting "display system time with seconds" and return such value directly from GetSysTime, should be much cleaner. This will also go into the GUI settings then.

**Comment by mskalski** [comment]
OK, thanks.

@herrnst I had some thoughts about possibility of displaying system clock in different formats:
`HH:MM:SS` (as for now, when there is enough space)
`H:MM:SS` (don't display leading zero in hours)

`HH:MM` (as I implemented with setting `fourdigitbigclock` in `LCDd.xml`) - with leading zeros
`H:MM` - same but without leading zero in hour field

For completeness also `HH` and `H` would be also interesting :-)

What do you think about incorporating this feature in GUI? Shall I open new feature request?

**Pull request closed without merging**
