### PR TITLE
fr translations: fixes

### PR DESCRIPTION
**Pull request by fengalin**

### CODE REVIEW

**Comment by herrnst** [comment]
Thanks!

**Comment by herrnst** [comment]
@fengalin Hi, jfyi, script.xbmc.lcdproc-3.0.0 for leia, containing your translation, was just released with a bulk of other cleanups and is already pushed to Kodi's addon repo.

**Comment by fengalin** [comment]
Awesome! Will try this now. Thanks!

**Comment by fengalin** [comment]
Works great! It seems that you also fixed the time issue in screen saver, previously it was displaying `00:00` in big digits (except with a paused video). I looked a bit when I discovered this, but didn't find anything obvious. Thanks again!

**Comment by herrnst** [comment]
Thanks for your feedback, much appreciated (and of course let me know if anything goes wrong so things can be fixed up further!). The clock issue was actually caused by a change in Kodi where the state of "Playing" and "Paused" is now set differently than in Krypton and earlier. That one was a bit tricky but not that hard after getting a hang of it :) In code terms, the fix is a combination of https://github.com/herrnst/script.xbmc.lcdproc/commit/406ebd1133ceac08500e1b6d7caf1b99734a302c and https://github.com/herrnst/script.xbmc.lcdproc/commit/dcb673eb86a764c367aaae84e471e0a405447a42 .

**Comment by fengalin** [comment]
Thanks for the pointers!

**Pull request merged**
