### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by fengalin**

### CODE REVIEW

**Comment by fengalin** [comment]
Closing since it will probably never be merged. Commit available in [my fork](https://github.com/fengalin/script.xbmc.lcdproc) in case someone is interested.

**Comment by herrnst** [comment]
@fengalin Sorry for not getting back to you on this earlier, been extra-busy with all kinds of different things, one of them bringing an uptodate ddbridge driver into the mainline kernel sources, and reallife brought a new job etc...

Are you still interested in getting the french translation into the addon?

**Comment by fengalin** [comment]
No problem, I know how what it means to contribute to open source!

Yes, I'm still interested in having the French translation merged. For my personal use, I also need https://github.com/herrnst/script.xbmc.lcdproc/pull/42 though. Do  you think it could also make its way to the next version?

**Comment by herrnst** [comment]
Okay, I'll take a closer look at the translation patch, and if it's all good, I'll merge it into the leia branch (which btw only exists since today :-) )

Re the screensaver thing, what exactly are you trying to achieve there? While checking the screensaver/generaldisplay/bigdigit stuff in the addon today, I noticed that (at least in leia) when playing back music, either some visualisation will start at some point, or (when paused) it just stays in that screen forever, but the screensaver isn't triggered at all...

**Comment by herrnst** [comment]
@fengalin I've applied your translation to the Leia branch, for now minus the music/screensaver translation string. I guess that one needs a bit more investigation (as mentioned, I wonder if its needed at all in Leia).

Thanks for your contribution, and sorry again that you had to wait that long.

**Comment by fengalin** [comment]
Thanks @herrnst.

I'm using Kodi as distributed by OSMC, so it might not be an issue with the upstream Leia version. I use a 2 lines OLED display (see [this photo](https://github.com/fengalin/raspdac-on-osmc#raspdac-running-osmc-playing-music)). My issue is that during playback, after 3 mn, the screen switches to current track's playing time with big digits so you can't check the title being played. It remains like this unless I interact with Kodi, hence the screen saver mode I was referring too. It's not screen saver in the sense that it doesn't show the time of day, but it is tied to the screen saver as this is triggered / remains like this when the HDMI display is switched to screen saver.

**Comment by herrnst** [comment]
Oh, just realised the behaviour is the same with Leia, after finding out what might be the difference between yours and my configuration :-)

I normally have a musicvis enabled, and this, together with "Settings -> UI -> Screensaver -> Use Visualization when playing music" prevents the screensaver from kicking in. When no vis is selected, the screensaver comes up after the configured period.

Wouldn't that be an option for you to simply have something like opengl spectrum or shadertoy enabled?

**Comment by fengalin** [comment]
Yes you're right! Installing the spectrum visualization and enabling `Settings -> Interface -> Screensaver -> Use visualization if playing audio` does the trick. I don't need my workaround any more. Thanks!

**Comment by herrnst** [comment]
Glad this works for you :-) Moving forward to get a release out for Leia then.

**Comment by fengalin** [comment]
Awesome!

**Comment by fengalin** [comment]
Yes no problem! I'd like to fix a couple of translation bits if it's OK with you though. I can do it now.

**Comment by herrnst** [comment]
Of course, just be sure to PR against the Leia branch and the PO file. Thanks!

**Pull request closed without merging**
